apiVersion: skupper.io/v2alpha1
kind: AttachedConnector
metadata:
  name: postgresql-east
  namespace: east-internal
spec:
  port: 5432
  selector: application=postgresql
  siteNamespace: east
  type: tcp
